"""Client/target dimension for the findings browser (issue #54).

Multi-client audits lay outputs out per target directory
(``outputs/<client>/03_PARTIAL_*.json``). Crucially, ``property_id`` is
generated by Phase 01e from the *spec* (``{prefix}-{type}-{seq}``), so the
SAME property_id legitimately appears in EVERY client's outputs — that is
the normal shape of the data, and these tests pin it:

1. The same property_id under two clients yields TWO findings (dedup is
   keyed on ``(target, property_id)``, never property_id alone).
2. ``meta.targets`` lists every distinct client (from the *unfiltered* set).
3. ``?target=<client>`` narrows the list to that client only.
4. The detail endpoint accepts ``?target=`` so a spec-derived property_id
   that exists for several clients resolves unambiguously.
5. Top-level ``outputs/03_PARTIAL_*.json`` (single-target layout) yields
   ``target: null`` and an empty ``meta.targets`` — the frontend then hides
   the client filter, so existing single-target runs are unaffected.

We redirect ``SPECA_OUTPUTS_DIR`` at the loader module so the tests never
touch the real ``outputs/`` tree.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from web.server.services import finding_loader


def _write_partial(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _audit_partial(property_id: str, severity: str, code_path: str) -> dict:
    return {
        "metadata": {"phase": "03", "timestamp": 1700000000},
        "audit_items": [
            {
                "property_id": property_id,
                "severity": severity,
                "code_path": code_path,
            }
        ],
    }


# One spec-derived property audited against two clients — the SAME id in
# both output dirs. This is the core multi-client shape.
SHARED_PROP = "PROP-txval-inv-001"


def _seed_multi_client(outputs: Path) -> None:
    _write_partial(
        outputs / "lighthouse_fusaka" / "03_PARTIAL_W0B0_1700000001.json",
        _audit_partial(SHARED_PROP, "Critical", "src/lh/validate.rs::L10-L20"),
    )
    _write_partial(
        outputs / "reth_fusaka" / "03_PARTIAL_W0B0_1700000002.json",
        _audit_partial(SHARED_PROP, "Medium", "src/reth/validate.rs::L30-L40"),
    )


def test_same_property_id_across_clients_yields_one_finding_per_client(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Dedup must key on (target, property_id) — no cross-client collapse."""

    outputs = tmp_path / "outputs"
    outputs.mkdir()
    _seed_multi_client(outputs)
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    body = client.get("/api/runs/any/findings").json()
    assert body["meta"]["count"] == 2
    rows = [f for f in body["data"] if f["property_id"] == SHARED_PROP]
    assert len(rows) == 2
    by_target = {f["target"]: f for f in rows}
    assert set(by_target) == {"lighthouse_fusaka", "reth_fusaka"}
    # Each client keeps its own record — severity / location not merged.
    assert by_target["lighthouse_fusaka"]["severity"] == "Critical"
    assert by_target["lighthouse_fusaka"]["file"] == "src/lh/validate.rs"
    assert by_target["reth_fusaka"]["severity"] == "Medium"
    assert by_target["reth_fusaka"]["file"] == "src/reth/validate.rs"


def test_meta_targets_lists_every_client_sorted(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    outputs = tmp_path / "outputs"
    outputs.mkdir()
    _seed_multi_client(outputs)
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    body = client.get("/api/runs/any/findings").json()
    assert body["meta"]["targets"] == ["lighthouse_fusaka", "reth_fusaka"]


def test_target_filter_narrows_to_one_client_each(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    outputs = tmp_path / "outputs"
    outputs.mkdir()
    _seed_multi_client(outputs)
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    for tgt in ("lighthouse_fusaka", "reth_fusaka"):
        body = client.get(f"/api/runs/any/findings?target={tgt}").json()
        assert body["meta"]["count"] == 1
        assert body["data"][0]["property_id"] == SHARED_PROP
        assert body["data"][0]["target"] == tgt
        # meta.targets stays the *full* set even when the list is filtered.
        assert body["meta"]["targets"] == ["lighthouse_fusaka", "reth_fusaka"]


def test_detail_lookup_disambiguates_by_target(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """?target= pins the exact per-client record for a shared property_id."""

    outputs = tmp_path / "outputs"
    outputs.mkdir()
    _seed_multi_client(outputs)
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    reth = client.get(
        f"/api/runs/any/findings/{SHARED_PROP}?target=reth_fusaka"
    ).json()
    assert reth["target"] == "reth_fusaka"
    assert reth["severity"] == "Medium"

    lh = client.get(
        f"/api/runs/any/findings/{SHARED_PROP}?target=lighthouse_fusaka"
    ).json()
    assert lh["target"] == "lighthouse_fusaka"
    assert lh["severity"] == "Critical"

    # Unknown client -> 404, not a silent fallback to another client's row.
    missing = client.get(f"/api/runs/any/findings/{SHARED_PROP}?target=nope")
    assert missing.status_code == 404


def test_top_level_outputs_have_null_target(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    outputs = tmp_path / "outputs"
    outputs.mkdir()
    # Single-target layout: PARTIAL sits directly under outputs/.
    _write_partial(
        outputs / "03_PARTIAL_W0B0_1700000003.json",
        _audit_partial("PROP-single-001", "High", "src/x.rs::L1-L2"),
    )
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    body = client.get("/api/runs/any/findings").json()
    assert body["data"][0]["target"] is None
    assert body["meta"]["targets"] == []
    # Bare detail lookup (no ?target=) still works for single-target runs.
    detail = client.get("/api/runs/any/findings/PROP-single-001")
    assert detail.status_code == 200
    assert detail.json()["target"] is None


def test_phase04_still_wins_within_one_client(
    client: TestClient,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The 04-beats-03 merge still applies inside a (target, property_id) bucket."""

    outputs = tmp_path / "outputs"
    outputs.mkdir()
    _seed_multi_client(outputs)
    # Phase 04 review for the lighthouse copy only.
    _write_partial(
        outputs / "lighthouse_fusaka" / "04_PARTIAL_W0B0_1700000005.json",
        {
            "metadata": {"phase": "04", "timestamp": 1700000005},
            "reviewed_items": [
                {
                    "property_id": SHARED_PROP,
                    "review_verdict": "CONFIRMED_VULNERABILITY",
                    "adjusted_severity": "High",
                }
            ],
        },
    )
    monkeypatch.setattr(finding_loader, "SPECA_OUTPUTS_DIR", outputs)

    body = client.get("/api/runs/any/findings").json()
    assert body["meta"]["count"] == 2  # still one row per client
    by_target = {f["target"]: f for f in body["data"]}
    lh = by_target["lighthouse_fusaka"]
    assert lh["phase"] == "04"
    assert lh["verdict"] == "CONFIRMED_VULNERABILITY"
    assert lh["severity"] == "High"
    # Phase 03 context (code location) survives the merge.
    assert lh["file"] == "src/lh/validate.rs"
    # The reth copy is untouched by lighthouse's review.
    reth = by_target["reth_fusaka"]
    assert reth["phase"] == "03"
    assert reth["verdict"] is None
